export const regionData: { uid: number; name: string; name_en: string }[] = [
  { uid: 3, name: "Хмельницька область", name_en: "Khmelnytskyi Oblast" },
  { uid: 4, name: "Вінницька область", name_en: "Vinnytsia Oblast" },
  { uid: 5, name: "Рівненська область", name_en: "Rivne Oblast" },
  { uid: 8, name: "Волинська область", name_en: "Volyn Oblast" },
  {
    uid: 9,
    name: "Дніпропетровська область",
    name_en: "Dnipropetrovsk Oblast",
  },
  { uid: 10, name: "Житомирська область", name_en: "Zhytomyr Oblast" },
  { uid: 11, name: "Закарпатська область", name_en: "Zakarpattia Oblast" },
  { uid: 12, name: "Запорізька область", name_en: "Zaporizhia Oblast" },
  {
    uid: 13,
    name: "Івано-Франківська область",
    name_en: "Ivano-Frankivsk Oblast",
  },
  { uid: 14, name: "Київська область", name_en: "Kyiv Oblast" },
  { uid: 15, name: "Кіровоградська область", name_en: "Kirovohrad Oblast" },
  { uid: 16, name: "Луганська область", name_en: "Luhansk Oblast" },
  { uid: 17, name: "Миколаївська область", name_en: "Mykolaiv Oblast" },
  { uid: 18, name: "Одеська область", name_en: "Odesa Oblast" },
  { uid: 19, name: "Полтавська область", name_en: "Poltava Oblast" },
  { uid: 20, name: "Сумська область", name_en: "Sumy Oblast" },
  { uid: 21, name: "Тернопільська область", name_en: "Ternopil Oblast" },
  { uid: 22, name: "Харківська область", name_en: "Kharkiv Oblast" },
  { uid: 23, name: "Херсонська область", name_en: "Kherson Oblast" },
  { uid: 24, name: "Черкаська область", name_en: "Cherkasy Oblast" },
  { uid: 25, name: "Чернігівська область", name_en: "Chernihiv Oblast" },
  { uid: 26, name: "Чернівецька область", name_en: "Chernivtsi Oblast" },
  { uid: 27, name: "Львівська область", name_en: "Lviv Oblast" },
  { uid: 28, name: "Донецька область", name_en: "Donetsk Oblast" },
  {
    uid: 29,
    name: "Автономна Республіка Крим",
    name_en: "Autonomous Republic of Crimea",
  },
  { uid: 31, name: "м. Київ", name_en: "Kyiv" },
  { uid: 32, name: "Тульчинський район", name_en: "Tulchyn District" },
  {
    uid: 33,
    name: "Могилів-Подільський район",
    name_en: "Mohyliv-Podilskyi District",
  },
  { uid: 34, name: "Хмільницький район", name_en: "Khmelnytskyi District" },
  { uid: 35, name: "Жмеринський район", name_en: "Zhmerinka District" },
  { uid: 36, name: "Вінницький район", name_en: "Vinnytsia District" },
  { uid: 37, name: "Гайсинський район", name_en: "Haivsyn District" },
  { uid: 38, name: "Володимирський район", name_en: "Volodymyr District" },
  { uid: 39, name: "Луцький район", name_en: "Lutsk District" },
  { uid: 40, name: "Ковельський район", name_en: "Kovel District" },
  {
    uid: 41,
    name: "Камінь-Каширський район",
    name_en: "Kamyanske-Kashyrskyi District",
  },
  { uid: 42, name: "Камянський район", name_en: "Kamianske District" },
  { uid: 43, name: "Самарівський район", name_en: "Samaryvskyi District" },
  { uid: 44, name: "Дніпровський район", name_en: "Dnipro District" },
  { uid: 45, name: "Павлоградський район", name_en: "Pavlohrad District" },
  { uid: 46, name: "Криворізький район", name_en: "Kryvyi Rih District" },
  { uid: 47, name: "Нікопольський район", name_en: "Nikopol District" },
  { uid: 48, name: "Синельниківський район", name_en: "Synelnykove District" },
  { uid: 49, name: "Кальміуський район", name_en: "Kalmius District" },
  { uid: 50, name: "Краматорський район", name_en: "Kramatorsk District" },
  { uid: 51, name: "Горлівський район", name_en: "Horlivka District" },
  { uid: 52, name: "Маріупольський район", name_en: "Mariupol District" },
  { uid: 53, name: "Донецький район", name_en: "Donetsk District" },
  { uid: 54, name: "Бахмутський район", name_en: "Bakhmut District" },
  { uid: 55, name: "Волноваський район", name_en: "Volnovakha District" },
  { uid: 56, name: "Покровський район", name_en: "Pokrovsk District" },
  { uid: 57, name: "Бердичівський район", name_en: "Berdychiv District" },
  { uid: 58, name: "Коростенський район", name_en: "Korosten District" },
  { uid: 59, name: "Житомирський район", name_en: "Zhytomyr District" },
  { uid: 60, name: "Звягельський район", name_en: "Zvyaghel District" },
  { uid: 61, name: "Берегівський район", name_en: "Berehove District" },
  { uid: 62, name: "Хустський район", name_en: "Khust District" },
  { uid: 63, name: "Рахівський район", name_en: "Rakhiv District" },
  { uid: 64, name: "Тячівський район", name_en: "Tyachiv District" },
  { uid: 65, name: "Мукачівський район", name_en: "Mukachevo District" },
  { uid: 66, name: "Ужгородський район", name_en: "Uzhhorod District" },
  { uid: 67, name: "Верховинський район", name_en: "Verkhovyna District" },
  {
    uid: 68,
    name: "Івано-Франківський район",
    name_en: "Ivano-Frankivsk District",
  },
  { uid: 69, name: "Косівський район", name_en: "Kosiv District" },
  { uid: 70, name: "Коломийський район", name_en: "Kolomyia District" },
  { uid: 71, name: "Калуський район", name_en: "Kalush District" },
  { uid: 72, name: "Надвірнянський район", name_en: "Nadvirna District" },
  { uid: 73, name: "Білоцерківський район", name_en: "Bila Tserkva District" },
  { uid: 74, name: "Вишгородський район", name_en: "Vyshhorod District" },
  { uid: 75, name: "Бучанський район", name_en: "Bucha District" },
  { uid: 76, name: "Обухівський район", name_en: "Obukhiv District" },
  { uid: 77, name: "Фастівський район", name_en: "Fastiv District" },
  { uid: 78, name: "Бориспільський район", name_en: "Boryspil District" },
  { uid: 79, name: "Броварський район", name_en: "Brovary District" },
  { uid: 80, name: "Олександрійський район", name_en: "Oleksandriya District" },
  { uid: 81, name: "Кропивницький район", name_en: "Kropyvnytskyi District" },
  { uid: 82, name: "Голованівський район", name_en: "Holovanyvskyi District" },
  { uid: 83, name: "Новоукраїнський район", name_en: "Novoukrainka District" },
  {
    uid: 84,
    name: "Сіверськодонецький район",
    name_en: "Severodonetsk District",
  },
  { uid: 85, name: "Сватівський район", name_en: "Svatove District" },
  { uid: 86, name: "Старобільський район", name_en: "Starobilsk District" },
  { uid: 87, name: "Щастинський район", name_en: "Shchastya District" },
  { uid: 88, name: "Самбірський район", name_en: "Sambir District" },
  { uid: 89, name: "Стрийський район", name_en: "Stryi District" },
  { uid: 90, name: "Львівський район", name_en: "Lviv District" },
  { uid: 91, name: "Дрогобицький район", name_en: "Drohobych District" },
  { uid: 92, name: "Шептицький район", name_en: "Sheptytskyi District" },
  { uid: 93, name: "Яворівський район", name_en: "Yavoriv District" },
  { uid: 94, name: "Золочівський район", name_en: "Zolochiv District" },
  { uid: 95, name: "Вознесенський район", name_en: "Voznesensk District" },
  { uid: 96, name: "Баштанський район", name_en: "Bastan District" },
  { uid: 97, name: "Первомайський район", name_en: "Pervomaisk District" },
  { uid: 98, name: "Миколаївський район", name_en: "Mykolaiv District" },
  { uid: 99, name: "Подільський район", name_en: "Podil District" },
  { uid: 100, name: "Березівський район", name_en: "Berezivskyi District" },
  { uid: 101, name: "Ізмаїльський район", name_en: "Izmail District" },
  {
    uid: 102,
    name: "Білгород-Дністровський район",
    name_en: "Bilhorod-Dnistrovskyi District",
  },
  { uid: 103, name: "Роздільнянський район", name_en: "Rozdilna District" },
  { uid: 104, name: "Одеський район", name_en: "Odesa District" },
  { uid: 105, name: "Болградський район", name_en: "Bolgad District" },
  { uid: 106, name: "Лубенський район", name_en: "Lubny District" },
  { uid: 107, name: "Кременчуцький район", name_en: "Kremenchuk District" },
  { uid: 108, name: "Миргородський район", name_en: "Myhorod District" },
  { uid: 109, name: "Полтавський район", name_en: "Poltava District" },
  { uid: 110, name: "Вараський район", name_en: "Varash District" },
  { uid: 111, name: "Дубенський район", name_en: "Dubno District" },
  { uid: 112, name: "Рівненський район", name_en: "Rivne District" },
  { uid: 113, name: "Сарненський район", name_en: "Sarny District" },
  { uid: 114, name: "Сумський район", name_en: "Sumy District" },
  { uid: 115, name: "Шосткинський район", name_en: "Shostka District" },
  { uid: 116, name: "Роменський район", name_en: "Romny District" },
  { uid: 117, name: "Конотопський район", name_en: "Konotop District" },
  { uid: 118, name: "Охтирський район", name_en: "Okhtyrka District" },
  { uid: 119, name: "Тернопільський район", name_en: "Ternopil District" },
  { uid: 120, name: "Кременецький район", name_en: "Kremenets District" },
  { uid: 121, name: "Чортківський район", name_en: "Chortkiv District" },
  { uid: 122, name: "Чугуївський район", name_en: "Chuhuiv District" },
  { uid: 123, name: "Купянський район", name_en: "Kupiansk District" },
  { uid: 124, name: "Харківський район", name_en: "Kharkiv District" },
  { uid: 125, name: "Ізюмський район", name_en: "Izyum District" },
  { uid: 126, name: "Богодухівський район", name_en: "Bohodukhiv District" },
  { uid: 127, name: "Берестинський район", name_en: "Berestynskyi District" },
  { uid: 128, name: "Лозівський район", name_en: "Lozivskyi District" },
  { uid: 129, name: "Бериславський район", name_en: "Beryslav District" },
  { uid: 130, name: "Скадовський район", name_en: "Skadovsk District" },
  { uid: 131, name: "Каховський район", name_en: "Kakhovka District" },
  { uid: 132, name: "Херсонський район", name_en: "Kherson District" },
  { uid: 133, name: "Генічеський район", name_en: "Henichesk District" },
  { uid: 134, name: "Хмельницький район", name_en: "Khmelnytskyi District" },
  {
    uid: 135,
    name: "Камянець-Подільський район",
    name_en: "Kamianets-Podilskyi District",
  },
  { uid: 136, name: "Шепетівський район", name_en: "Shepetivka District" },
  { uid: 137, name: "Чернівецький район", name_en: "Chernivtsi District" },
  { uid: 138, name: "Вижницький район", name_en: "Vyzhnytsia District" },
  { uid: 139, name: "Дністровський район", name_en: "Dnister District" },
  { uid: 140, name: "Чернігівський район", name_en: "Chernihiv District" },
  {
    uid: 141,
    name: "Новгород-Сіверський район",
    name_en: "Novhorod-Siverskyi District",
  },
  { uid: 142, name: "Ніжинський район", name_en: "Nizhyn District" },
  { uid: 143, name: "Прилуцький район", name_en: "Priluky District" },
  { uid: 144, name: "Корюківський район", name_en: "Korukivka District" },
  { uid: 145, name: "Пологівський район", name_en: "Polohiv District" },
  { uid: 146, name: "Маріупольський район", name_en: "Mariupol District" },
  { uid: 147, name: "Покровський район", name_en: "Pokrovsk District" },
  { uid: 148, name: "Добропільський район", name_en: "Dobropil District" },
  { uid: 149, name: "Миколаївський район", name_en: "Mykolaiv District" },
  { uid: 150, name: "Мелітопольський район", name_en: "Melitopol District" },
  { uid: 151, name: "Запорізький район", name_en: "Zaporizhia District" },
  { uid: 152, name: "Черкаський район", name_en: "Cherkasy District" },
  { uid: 153, name: "Золотоніський район", name_en: "Zolotonosha District" },
  { uid: 564, name: "м. Запоріжжя", name_en: "Zaporizhzhia" },
  { uid: 1293, name: "м. Харків", name_en: "Kharkiv" },
];
